using System;
using System.Collections.Generic;
using System.Text;

namespace universityBD
{
    class DepartmentNames
    {
        public static List<String> GetListOfNames()
        {
            return Names;
        }

        private readonly static List<String> Names = new List<string> {
            "Department of Chemical Engineering and Applied Chemistry",
            "Department of Civil and Mineral Engineering",
            "Edward S. Rogers Sr. Department of Electrical and Computer Engineering",
            "Department of Materials Science and Engineering",
            "Department of Mechanical and Industrial Engineering",
            "Department of Anthropology",
            "Department of Art History",
            "David A. Dunlap Department of Astronomy and Astrophysics",
            "Department of Cell and Systems Biology",
            "Department of Chemistry",
            "Department of Classics",
            "Department of Computer Science",
            "Department of East Asian Studies",
            "Department of Ecology and Evolutionary Biology",
            "Department of Economics",
            "Department of English",
            "Department of French",
            "Department of Geography and Planning",
            "Department of Earth Sciences",
            "Department of Germanic Languages and Literatures",
            "Department of History",
            "Department of Italian Studies",
            "Department of Linguistics",
            "Department of Mathematics",
            "Department of Near and Middle Eastern Civilizations",
            "Department of Philosophy",
            "Department of Physics",
            "Department of Political Science",
            "Department of Psychology",
            "Department for the Study of Religion",
            "Department of Slavic Languages and Literatures",
            "Department of Sociology",
            "Department of Spanish and Portuguese",
            "Department of Statistical Sciences",
            "Department of Anesthesiology and Pain Medicine",
            "Department of Biochemistry",
            "Department of Family and Community Medicine",
            "Department of Immunology",
            "Department of Laboratory Medicine and Pathobiology",
            "Department of Medical Biophysics",
            "Department of Medical Imaging",
            "Department of Medicine",
            "Department of Molecular Genetics",
            "Department of Nutritional Sciences",
            "Department of Obstetrics and Gynaecology",
            "Department of Occupational Science and Occupational Therapy",
            "Department of Ophthalmology and Vision Sciences",
            "Department of Otolaryngology - Head and Neck Surgery",
            "Department of Paediatrics",
            "Department of Pharmacology and Toxicology",
            "Department of Physical Therapy",
            "Department of Physiology",
            "Department of Psychiatry",
            "Department of Radiation Oncology",
            "Department of Speech-Language Pathology",
            "Department of Surgery",
            "Department of Curriculum, Teaching and Learning",
            "Department of Applied Psychology and Human Development",
            "Department of Social Justice Education",
            "Department of Leadership, Higher and Adult Education",
            "Department of Anthropology",
            "Department of Biology",
            "Department of Chemical and Physical Sciences",
            "Department of Economics",
            "Department of English and Drama",
            "Department of Geography",
            "Department of Historical Studies",
            "Department of Language Studies",
            "Department of Management",
            "Department of Mathematical and Computational Sciences",
            "Department of Philosophy",
            "Department of Political Science",
            "Department of Psychology",
            "Department of Sociology",
            "Department of Visual Studies",
            "Department of Management",
            "Department of English",
            "Department of Philosophy",
            "Department of Biological Sciences",
            "Department of Computer and Mathematical Sciences",
            "Department of Psychology",
            "Department of Physical and Environmental Sciences",
            "Department of Anthropology",
            "Department of Human Geography",
            "Department of Political Science",
            "Department of Sociology",
            "Department of Arts, Culture and Media",
            "Department of Historical and Cultural Studies"
        }; // Data taken from https://www.vpacademic.utoronto.ca/academic-units/academic-unit-list-departments-edus/
    }
}
